### ISSUE TITLE
JavaIO http error for api url

### ISSUE THREAD

**Issue by mattlev** [MinecraftForge/Mercurius#7]
Repeatedly getting 500 or 504 errors from the stats api url which positively spams output over a decent period of time.  Running FTB Beyond 1.8.1 pack on minecraft 1.10.2.

[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]: java.io.IOException: Server returned HTTP response code: 504 for URL
: http://stats.minecraftforge.net/api/v2/
[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStrea
m0(HttpURLConnection.java:1876)
[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at sun.net.www.protocol.http.HttpURLConnection.access$200(Ht
tpURLConnection.java:91)
[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURL
Connection.java:1466)
[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURL
Connection.java:1464)
[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at java.security.AccessController.doPrivileged(Native Method
)
[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at java.security.AccessController.doPrivilegedWithCombiner(A
ccessController.java:782)
[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStrea
m(HttpURLConnection.java:1463)
[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at net.minecraftforge.mercurius.Sender.post(Sender.java:130)
[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at net.minecraftforge.mercurius.Sender.access$000(Sender.jav
a:25)
[16:28:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at net.minecraftforge.mercurius.Sender$1.run(Sender.java:104
)
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]: java.io.IOException: Server returned HTTP response code: 500 for URL
: http://stats.minecraftforge.net/api/v2/
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStrea
m0(HttpURLConnection.java:1876)
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at sun.net.www.protocol.http.HttpURLConnection.access$200(Ht
tpURLConnection.java:91)
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender
:post:148]:         at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURL
Connection.java:1466)
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender:post:148]:         at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender:post:148]:         at java.security.AccessController.doPrivileged(Native Method)
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender:post:148]:         at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender:post:148]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender:post:148]:         at net.minecraftforge.mercurius.Sender.post(Sender.java:130)
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender:post:148]:         at net.minecraftforge.mercurius.Sender.access$000(Sender.java:25)
[16:42:49] [MercuriusThread/INFO] [STDERR]: [net.minecraftforge.mercurius.Sender:post:148]:         at net.minecraftforge.mercurius.Sender$1.run(Sender.java:104)

**Comment by ironrainomega** [comment]
Fixed in 1.0.6. Though the backend shouldn't be erroring so much. Let me ping a few folks.
